### ISSUE TITLE
History asking to remove too old blobs crash

### ISSUE THREAD

**Issue by Breush** [wanadev/obsidian-project#26]
## Description

- Add a blob to the project with history enabled.
- Snapshot.
- Remove the blob from the project.
- Make snapshots until the maxLength of the history is hit.
- It crashes instead of removing the blob.

## Log

```
Uncaught TypeError: Cannot set property 'd2c18aa1-00d2-4baf-88c8-6cb789835145' of undefined
    at __class__._cropLength (history.js:245)
    at __class__.snapshot (history.js:82)
```

**Comment by flozz** [comment]
Fixed in v3.1.2
