### ISSUE TITLE
Problème unserialize plan

### ISSUE THREAD

**Issue by acroix** [wanadev/obsidian-project#44]
Bonjour,

Je rencontre des problèmes pour récupérer l'objet d'un plan
Dans un premier temps je récupère le buffer du plan et j'essai ensuite d'utiliser la méthode openFromBuffer qui me renvoi des erreurs.

Voici le code en question

```javascript
const axios = require('axios');
const ProjectManager = require('obsidian-project/lib/project-manager');

module.exports = async (url) => {
  try {
    const buffer = await axios.get(url, { responseType: 'arraybuffer' });

    const project = new ProjectManager({
      fileExt: 'wprj', // Default extention for generated files (e.g. "kzd", "wnp",...)
      metadata: {
        // any metadata you want
      },
    });

    const planData = project.openFromBuffer(buffer.data);

    return planData;
  } catch (err) {
    throw err;
  }
};
```

Problèmes rencontrés: 

1. Soucis au niveau du nom de projet
Dans la classe Serializable au test suivant : 
```javascript
 if (data.__name__ !== this.__name__) {
            throw new TypeError("WrongClassUnserialization");
}
```

data.__name__ = "wnp/project"
this.__name__ = "Project"

2. serializer.serializers[data.__name__] undefined
Toujours dans la même classe: 
```javascript
"$unserialize": function (data) {
            if (!data.__name__ || !serializer.serializers[data.__name__]) {
                throw new Error("MissingSerializer");
            }
            var sc = new serializer.serializers[data.__name__].class();
            sc.unserialize(data);
            return sc;
        },
```

Chez moi data.__name__ = "ground" et c'est peut-être l'origine du problème ?
Je n'ai pas pu aller plus loin

Merci d'avance pour votre aide

**Comment by fryck** [comment]
@clementlevasseur De notre côté, si on peut éviter de re-coder la logique ce serait top, car actuellement on refait la moulinette pour récupérer le JSON chez nous, et c'est dommage.. :)

**Comment by flozz** [comment]
We discussed this issue on an other medium, I close it :)
